services:
  - type: web
    name: social-assistance-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: python -m gunicorn wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: 'False'
      - key: DISABLE_COLLECTSTATIC
        value: '1'
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: '4'
