# Generated by Django 5.2.1 on 2025-06-04 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='nome da família')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='estado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações gerais')),
                ('recebe_programas_sociais', models.BooleanField(default=False, verbose_name='recebe programas sociais?')),
                ('programas_sociais', models.TextField(blank=True, null=True, verbose_name='quais programas sociais?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'família',
                'verbose_name_plural': 'famílias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='nome completo')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='sexo')),
                ('parentesco', models.CharField(blank=True, max_length=100, null=True, verbose_name='parentesco')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('nis', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIS')),
                ('estudando', models.BooleanField(default=False, verbose_name='está estudando?')),
                ('escola', models.CharField(blank=True, max_length=200, null=True, verbose_name='nome da escola')),
                ('serie_escolar', models.CharField(blank=True, max_length=50, null=True, verbose_name='série escolar')),
                ('declaracao_matricula', models.ImageField(blank=True, null=True, upload_to='membros/declaracoes_matricula/', verbose_name='declaração de matrícula')),
                ('foto_3x4', models.ImageField(blank=True, null=True, upload_to='membros/fotos_3x4/', verbose_name='foto 3x4')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='familias.familia', verbose_name='família')),
            ],
            options={
                'verbose_name': 'membro da família',
                'verbose_name_plural': 'membros da família',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='nome completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='sexo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('parentesco', models.CharField(blank=True, max_length=100, null=True, verbose_name='parentesco')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='familias.familia', verbose_name='família')),
            ],
            options={
                'verbose_name': 'responsável',
                'verbose_name_plural': 'responsáveis',
                'ordering': ['nome_completo'],
            },
        ),
    ]
