# Generated by Django 4.2.21 on 2025-06-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='parentesco',
        ),
    ]
