# Generated by Django 5.2.1 on 2025-06-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=15, null=True, verbose_name='RG')),
                ('nis', models.CharField(blank=True, max_length=15, null=True, verbose_name='NIS')),
                ('grau_parentesco', models.CharField(choices=[('PAI', 'Pai'), ('MAE', 'Mãe'), ('FILHO', 'Filho'), ('ESPOSO', 'Esposo'), ('ESPOSA', 'Esposa'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Grau de Parentesco')),
                ('declaracao_matricula', models.FileField(blank=True, null=True, upload_to='membros/declaracoes/', verbose_name='Declaração de Matrícula')),
                ('foto_3x4', models.ImageField(blank=True, null=True, upload_to='membros/fotos/', verbose_name='Foto 3x4')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_membros', to='familias.familia')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['nome'],
            },
        ),
    ]
