# Generated by Django 5.2.1 on 2025-06-04 10:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='data do encontro')),
                ('presente', models.BooleanField(default=True, verbose_name='presente')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='membros.membro', verbose_name='membro')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turmas.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'presença',
                'verbose_name_plural': 'presenças',
                'ordering': ['-data'],
                'constraints': [models.UniqueConstraint(fields=('membro', 'data'), name='unique_membro_data')],
            },
        ),
    ]
