# Generated by Django 5.2.1 on 2025-06-04 10:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaDeCesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField(default=datetime.date.today, verbose_name='data da entrega')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_de_cesta', to='familias.familia', verbose_name='família')),
            ],
            options={
                'verbose_name': 'entrega de cesta',
                'verbose_name_plural': 'entregas de cesta',
                'ordering': ['-data_entrega'],
                'constraints': [models.UniqueConstraint(fields=('familia', 'data_entrega'), name='unique_familia_data_entrega')],
            },
        ),
    ]
